# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feat
    - title: Bug fixes
      labels:
        - fix
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: 👒 Dependencies
      labels:
        - deps
    - title: Documentation updates
      label: 
        - docs
    - title: Other Changes
      labels:
        - "*"
